# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gloauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GloNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('textMessage', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_known_coordinates',
            field=models.CharField(default='uninitialized', max_length=100),
        ),
    ]
