# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gloauth', '0002_auto_20160204_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='glonote',
            name='image_filename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
